### ISSUE TITLE
blacklist some video drivers

### ISSUE THREAD

**Issue by psy0rz** [psy0rz/alpinebox#3]
I encountered a problem with no console output on older hardware:

```
[    8.379605] radeon 0000:01:05.0: vgaarb: deactivate vga console
```

After blacklisting it (And mkinitfs) it was fixed, so we should probably blacklist them all be default:

```
# Blacklist common GPU drivers
blacklist radeon
blacklist amdgpu
blacklist nouveau
blacklist nvidia
blacklist nvidiafb
blacklist rivafb
blacklist i915
blacklist intel_agp
blacklist drm
blacklist drm_kms_helper
```

**Comment by divStar** [comment]
Dude, while I haven't encountered this error, I am amazed how you leave such knowledge for people to find - this would be the first place I'd look if it wasn't directly Alpine related. Thank you! I hope AlpineBox works with the newest Alpine, too, because I am going to install it on my new server.

**Comment by psy0rz** [comment]
thanks! i'll make a pre-release for v3.21 so you can test it. (altough its easy to upgrade an older version of alpine)

**Comment by psy0rz** [comment]
it built, so try it (v3.21-2)

its prerelease so you have to specify the version to the installimage script

**Comment by divStar** [comment]
Thank so much for making it happen so quickly, I'll give it a try tonight.

Just a question, because I am not using a VPS, but a local server: do I just boot anything over IPMI (virtual USB drive) and then start the installation using the install script? I am a bit unsure, I did read the documentation, but I am a bit unsure how to go about it, especially if I only intend to use UEFI.

**Comment by psy0rz** [comment]
yeah, it doesnt even matter if you boot legacy or uefi, the image contains both and always works.

just boot something that can see the disk and run the shell script to write the image.
